### ISSUE TITLE
Found there is no implementation of ImpressionistDoc::set*

### ISSUE THREAD

**Issue by HaozhiQi** [JeffOwOSun/Impressionist#11]
Strange behavior, I fount that the get and set attribute functions are both declared on ImpressionistDoc and ImpressionistUI. However, there is no implementation for ImpressionistDoc::set\* and the implemenation of ImpressionistDoc::get\* only calls functions in ImpressionistUI. 

Seems this is not a tidy design, attribute should store in some reasonable place and the setter and getter should only be defined one. Right?

**Comment by JeffOwOSun** [comment]
I thinke the reason here is like this: Sliders generally belong to UI class, while Brushes belong to Doc class. When it comes to attributes like line width and brush size, they are both referenced in UI as value for slider and in Doc as parameters to draw. So we need get in both of them. But then you can only set them by dragging sliders, i.e. in UI class, so only UI needs to have set methods.
